project:
  type: website
  output-dir: docs
  resources:
    - "ring.js"
    - "data/ring.json"

execute:
    freeze: auto

website:
  title: "AffCom Lab"
  navbar:
    background: "#faf7f2"
    foreground: "#1c1a17"
    right:
      - href: news.qmd
        text: News
      - href: people.qmd
        text: People
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: resources.qmd
        text: Resources
      - href: opportunities.qmd
        text: Opportunities
      - href: contact.qmd
        text: Contact
  page-footer:
    left: "&copy; 2026 Jeffrey Girard"
    center: "Affective Communication & Computing Lab<br>Fraser Hall 455, University of Kansas, Lawrence, KS"
    right:
      - icon: envelope
        href: contact.html
        aria-label: Contact
      - icon: github
        aria-label: GitHub
        href: https://github.com/jmgirard/affcomlab
  google-analytics: "G-K5TXS64QLN"
  site-url: https://affcom.ku.edu
  repo-url: https://github.com/jmgirard/affcomlab

format:
  html:
    theme: [cosmo, theme.scss]
    toc: true
