---
title: "It’s the sentiment that counts: Comparing sentiment analysis tools for estimating affective valence in dream reports"
type: "article"
author: "Baber, Hamilton, et al."
year: "2024"
publication: "Sleep"
doi: "10.1093/sleep/zsae210"
toc: false
categories:
  - verbal
  - affective
  - article
---

## Citation (APA 7)

> Baber, G. R., Hamilton, N. A., Girard, J. M., Cohen, J. M., Gratton, M. K. P., Ellis, S., & Hemmer, E. (2024). It’s the sentiment that counts: Comparing sentiment analysis tools for estimating affective valence in dream reports. *Sleep, 47*(12), zsa210.

## Abstract

Despite advances in sleep and dream science via neuroscientific methods, self-reported diary data (e.g. dream journals) remain indispensable for capturing theory-relevant phenomenological aspects of dreams including their emotional content [1, 2]. Manual annotation of such data; however, is time-intensive and typically requires human coders to be trained to reliability. To circumvent these bottlenecks, sleep, and dream researchers can apply computational sentiment analysis techniques to automate the estimation of dream affect (DA) from dream journal text. Yet, there is currently no guide to aid dream researchers in selecting an appropriate sentiment analysis tool from among the many available for this task.

Sentiment analysis methods have been applied to dream reports with varying degrees of success [3, 4]. Lexicon-based approaches show low convergent validity in estimating externally annotated DA [3]. Large language models show more promise, but existing applications have not been validated against self-reported DA and produce categorical outcomes (e.g. most probable emotion) [4]. To address this gap in the literature, we compared four sentiment analysis approaches and hand-coded peer ratings in their ability to estimate dreamers’ self-reported DA. Because sentiment analysis tools varied in affective measures (i.e. continuous and categorical measures), we used principal components analyses (PCA) to reduce ratings of DA to a unidimensional measure of dream affective valence (DAV).
