---
title: "Alcohol and emotion: Analyzing convergence between facially expressed and self-reported indices of emotion under alcohol intoxication"
type: "article"
author: "Caumiant, Kang, Girard, & Fairbairn"
year: "2025"
publication: "Psychology of Addictive Behaviors"
doi: "https://psycnet.apa.org/doi/10.1037/adb0001053"
toc: false
categories:
  - nonverbal
  - clinical
  - article
---

## Citation (APA 7)

> Caumiant, E. P., Kang, D., Girard, J. M., & Fairbairn, C. E. (in press). Alcohol and emotion: Analyzing convergence between facially expressed and self-reported indices of emotion under alcohol intoxication. *Psychology of Addictive Behaviors.*

## Abstract

Objective: Emotion measurement is central to capturing acute alcohol reinforcement and so to informing models of alcohol use disorder etiology. Yet our understanding of how alcohol impacts emotion as assessed across diverse response modalities remains incomplete. The present study leverages a social alcohol-administration paradigm to assess drinking-related emotions, aiming to elucidate impacts of intoxication on self-reported versus behaviorally expressed emotion. Method: Participants (N = 60; Mage = 22.5; 50% male; 55% White) attended two counterbalanced laboratory sessions, on one of which they were administered an alcoholic beverage (target blood alcohol content .08%) and on the other a nonalcoholic control beverage. Participants in both conditions were accurately informed of beverage contents and consumed study beverages in assigned groups of three while their behavior was videotaped. Emotion was assessed via self-report as well as continuous coding of facial muscle movements. Results: The relationship between self-reported and behaviorally expressed emotion diverged significantly across beverage conditions: positive affect: b = −0.174, t = −2.36, p = .022; negative affect, b = 0.4319, t = 2.37, p = .021. Specifically, self-reports and behavioral displays converged among sober but not intoxicated participants. Further, alcohol’s effects on positive facial displays remained significant in models controlling for self-reported positive and negative emotion, with alcohol enhancing Duchenne smiles 20% beyond effects captured via self-reports, pointing to unique effects of alcohol on behavioral indicators of positive emotion. Conclusions: Findings highlight effects of acute intoxication on the convergence and divergence of emotion measures, thus informing our understanding of measures for capturing emotions that are most proximal to drinking and thus most immediately reinforcing of alcohol consumption.

## Impact Statement

This study indicates that, while participants’ self-reported and behaviorally expressed emotion held consistent when not drinking, these measures diverged following alcohol consumption. Results further indicated alcohol’s effects on positive emotion were not fully captured by self-report, a tool that has been relied on throughout addiction research. As a result, this study highlights the importance of using multiple methods of capturing emotion, including behavioral and self-report methods, when studying alcohol’s effects on emotion and drinking behaviors.
