---
title: "Depressive symptoms among Hispanic Americans: Investigating the interplay of acculturation and demographics"
type: "article"
author: "Rincon Caicedo, Girard, et al."
year: "2024"
publication: "Journal of Latinx Psychology"
doi: "https://doi.org/10.1037/lat0000266"
toc: false
categories:
  - clinical
  - article
---

## Citation (APA 7)

> Rincon Caicedo, M., Girard, J. M., Punt, S. E., Giovanetti, A. K., & Ilardi, S. S. (in press). Depressive symptoms among Hispanic Americans: Investigating the interplay of acculturation and demographics. *Journal of Latinx Psychology.*

## Abstract

As with many other racial and ethnic minorities, Hispanic Americans face substantial disparities in health care access and disease prevalence. The published literature on mental health disorders among Hispanic individuals, however, is not robust, and their experience of depressive disorders remains poorly understood. The construct of acculturation may help elucidate the risk of depression among Hispanic Americans and may inform the development of appropriate policy and treatment resources. We examined the degree to which acculturation may interact with key demographic variables (sex, age, socioeconomic status [SES], and Mexican ancestry) in accounting for depressive symptomatology among Hispanic Americans. We conducted a series of Bayesian generalized linear mixed models using data from the National Health and Nutrition Examination Survey to investigate the self-reported depressive symptomatology (measured by the Patient Health Questionnaire−9) of Mexican Americans and other Hispanic individuals and to examine possible effects of acculturation and demographics on depressive symptomatology in this population. Mexican Americans had substantially lower levels of depression than other Hispanic individuals. Acculturation was positively associated with depression severity, but this effect was moderated by sex and SES. High acculturation was more strongly linked to depression among men and those of high SES. Acculturation and several demographic factors were associated with depressive symptomatology among Hispanic individuals. Acculturation can be useful in understanding risk, developing culturally informed interventions, and implementing community-level changes to address the burden of Hispanic depression. 
