---
title: "Associations between transdiagnostic traits of psychopathology and hybrid posttraumatic stress disorder factors in a trauma-exposed community sample"
type: "article"
author: "Sprunger, Girard, & Chard"
year: "2024"
publication: "Journal of Traumatic Stress"
doi: "https://doi.org/10.1002/jts.23023"
materials: "https://osf.io/xn4w9/"
toc: false
categories:
  - clinical
  - article
---

## Citation (APA 7)

> Sprunger, J. G., Girard, J. M., & Chard, K. M. (2024). Associations between transdiagnostic traits of psychopathology and hybrid posttraumatic stress disorder factors in a trauma-exposed community sample. *Journal of Traumatic Stress*.


## Abstract

Dimensional conceptualizations of psychopathology hold promise for understanding the high rates of comorbidity with posttraumatic stress disorder (PTSD). Linking PTSD symptoms to transdiagnostic dimensions of psychopathology may enable researchers and clinicians to understand the patterns and breadth of behavioral sequelae following traumatic experiences that may be shared with other psychiatric disorders. To explore this premise, we recruited a trauma-exposed online community sample $(N = 462)$ and measured dimensional transdiagnostic traits of psychopathology using parceled facets derived from the Personality Inventory for DSM-5 Faceted–Short Form. PTSD symptom factors were measured using the PTSD Checklist for DSM-5 and derived using confirmatory factor analysis according to the seven-factor hybrid model (i.e., Intrusions, Avoidance, Negative Affect, Anhedonia, Externalizing Behaviors, Anxious Arousal, And Dysphoric Arousal). We observed hypothesized associations between PTSD factors and transdiagnostic traits indicating that some transdiagnostic dimensions were associated with nearly all PTSD symptom factors (e.g., emotional lability: rmean = .35), whereas others showed more unique relationships (e.g., hostility–Externalizing Behavior: $r = .60$; hostility with other PTSD factors: $r = .12–.31$). All PTSD factors were correlated with traits beyond those that would appear to be construct-relevant, suggesting the possibility of indirect associations that should be explicated in future research. The results indicate the breadth of trait-like consequences associated with PTSD symptom exacerbation, with implications for case conceptualization and treatment planning. Although PTSD is not a personality disorder, the findings indicate that increased PTSD factor severity is moderately associated with different patterns of trait-like disruptions in many areas of functioning.
