---
title: "MVAC Tutorial"
description: "Measurement Validation in Affective Computing"
author: "Jeffrey Girard"
date: "2023-09-10"
image: browser_stats.svg
draft: false
categories:
  - teaching
  - presentation
---

I gave a three-hour tutorial on Measurement Validation in Affective Computing at the Affective Computing and Intelligent Interaction (ACII 2023) conference in Boston, MA. Here are my slides:

<iframe class="slide-deck" src="./Presentation.html" title="Presentation Slides">
</iframe>

*Note.* To view the slideshow in full screen mode, click inside it and press the "f" key on your keyboard.<br />
You can also use the menu by clicking on the icon at the bottom-left of each slide.

## Recommended Articles

- Cizek, G. J. (2016). Validating test score meaning and defending test score use: Different aims, different methods. *Assessment in Education: Principles, Policy & Practice, 23*(2), 212–225. <https://doi.org/10.1080/0969594x.2015.1063479>

- Flake, J. K., & Fried, E. I. (2020). Measurement schmeasurement: Questionable measurement practices and how to avoid them. *Advances in Methods and Practices in Psychological Science, 3*(4), 456–465. <https://doi.org/10/ghnbdg>

- Flake, J. K., Pek, J., & Hehman, E. (2017). Construct validation in social and personality research: Current practice and recommendations. *Social Psychological and Personality Science, 8*(4), 370–378. <https://doi.org/10.1177/1948550617693063>

- Flora, D. B. (2020). Your coefficient alpha is probably wrong, but which coefficient omega is right? A tutorial on using R to obtain better reliability estimates. *Advances in Methods and Practices in Psychological Science, 3*(4), 484–501. <https://doi.org/10.1177/2515245920951747>

- Gehlbach, H., & Brinkworth, M. E. (2011). Measure twice, cut down error: A process for enhancing the validity of survey scales. *Review of General Psychology, 15*(4), 380–387. <https://doi.org/10/bnn2s3>

- Jacobucci, R., & Grimm, K. J. (2020). Machine Learning and Psychological Research: The Unexplored Effect of Measurement. *Perspectives on Psychological Science, 15*(3), 809–816. <https://doi.org/10/ghdp3b>

- Messick, S. (1995). Validity of psychological assessment: Validation of inferences from persons’ responses and performances as scientific inquiry into score meaning. *American Psychologist, 50*(9), 741–749. <https://doi.org/10.1037/0003-066x.50.9.741>

- Qiu, L., Chan, S. H. M., & Chan, D. (2017). Big data in social and psychological science: Theoretical and methodological issues. *Journal of Computational Social Science, 1*(1), 59–66. <https://doi.org/10.1007/s42001-017-0013-6>

- ten Hove, D., Jorgensen, T. D., & van der Ark, L. A. (2022). Updated guidelines on selecting an intraclass correlation coefficient for interrater reliability, with applications to incomplete observational designs. *Psychological Methods.* <https://doi.org/10.1037/met0000516>

- Weidman, A. C., Steckler, C. M., & Tracy, J. L. (2017). The jingle and jangle of emotion assessment: Imprecise measurement, casual scale usage, and conceptual fuzziness in emotion research. *Emotion, 17*(2), 267–295. <https://doi.org/10.1037/emo0000226>

## Recommended Books

- AERA, APA, & NCME. (2014). *Standards for educational and psychological testing.* American Educational Research Association. <https://www.testingstandards.net/open-access-files.html>

- Bowden, S. C. (Ed.). (2017). *Neuropsychological assessment in the age of evidence-based practice.* Oxford University Press.

- Brennan, R. L. (2001). *Generalizability theory.* Springer.

- Gwet, K. L. (2021). *Handbook of inter-rater reliability: Chance-corrected agreement coefficients* (5th ed., Vol. 1).

- Gwet, K. L. (2021). *Handbook of inter-rater reliability: Analysis of quantitative ratings* (5th ed., Vol. 2).

- Kline, R. (2015). *Principles and practice of structural equation modeling* (4th ed.). Guilford Press.

- Revelle, W. (2014). *An introduction to psychometric theory with applications in R.* <https://www.personality-project.org/r/book/>

- Zumbo, B. D., & Hubley, A. M. (Eds.). (2017). *Understanding and investigating response processes in validation research.* Springer.
