---
title: "Sayette group formation task (GFT) spontaneous facial expression database"
type: "proceeding"
author: "Girard, Chu, Jeni, et al."
year: "2017"
publication: "FG"
preprint: "https://psyarxiv.com/qfzsm/"
doi: "https://doi.org/10.1109/FG.2017.144"
materials: "https://osf.io/7wcyz/"
toc: false
categories:
  - methodological
  - observational
  - shared database
  - nonverbal behavior
  - emotion
  - proceeding
---

## Citation (APA 7)

> Girard, J. M., Chu, W.-S., Jeni, L. A., Cohn, J. F., De La Torre, F., & Sayette, M. A. (2017). Sayette Group Formation Task (GFT) Spontaneous Facial Expression Database. *Proceedings of the 12th IEEE International Conference on Automatic Face and Gesture Recognition (FG)*, 581–588.

## Abstract

Despite the important role that facial expressions play in interpersonal communication and our knowledge that interpersonal behavior is influenced by social context, no currently available facial expression database includes multiple interacting participants. The Sayette Group Formation Task (GFT) database addresses the need for well-annotated video of multiple participants during unscripted interactions. The database includes 172,800 video frames from 96 participants in 32 three-person groups. To aid in the development of automated facial expression analysis systems, GFT includes expert annotations of FACS occurrence and intensity, facial landmark tracking, and baseline results for linear SVM, deep learning, active patch learning, and personalized classification. Baseline performance is quantified and compared using identical partitioning and a variety of metrics (including means and confidence intervals). The highest performance scores were found for the deep learning and active patch learning methods. Learn more at <http://osf.io/7wcyz>
