---
title: "Historical heterogeneity predicts smiling: Evidence from large-scale observational analyses"
type: "proceeding"
author: "Girard & McDuff"
year: "2017"
publication: "FG"
preprint: "https://psyarxiv.com/49pxj/"
doi: "https://doi.org/10.1109/FG.2017.135"
materials: "https://osf.io/4zxms/"
toc: false
categories:
  - nonverbal
  - proceeding
---

## Citation (APA 7)

> Girard, J. M., & McDuff, D. (2017). Historical heterogeneity predicts smiling: Evidence from large-scale observational analyses. *Proceedings of the 12th IEEE International Conference on Automatic Face & Gesture Recognition (FG)*, 719–726.

## Abstract

Facial behavior is a valuable source of information about an individual’s feelings and intentions. However, many factors combine to influence and moderate facial behavior including personality, gender, context, and culture. Due to the high cost of traditional observational methods, the relationship between culture and facial behavior is not well-understood. In the current study, we explored the sociocultural factors that influence facial behavior using large-scale observational analyses. We developed and implemented an algorithm to automatically analyze the smiling of 866,726 participants across 31 different countries. We found that participants smiled more when from a country that is higher in individualism, has a lower population density, and has a long history of immigration diversity (i.e., historical heterogeneity). Our findings provide the first evidence that historical heterogeneity predicts actual smiling behavior. Furthermore, they converge with previous findings using selfreport methods. Taken together, these findings support the theory that historical heterogeneity explains, and may even contribute to the development of, permissive cultural display rules that encourage the open expression of emotion.
