---
title: "DynAMoS: The Dynamic Affective Movie Clip Database for Subjectivity Analysis"
type: "proceeding"
author: "Girard, Tie, & Liebenthal"
year: "2023"
publication: "ACII"
preprint: "https://jmgirard.github.io/dynamos/paper.html"
materials: "https://dynamos.mgb.org"
toc: false
categories:
  - database
  - affective
  - proceeding
---

## Citation (APA 7)

> Girard, J. M., Tie, Y., & Liebenthal, E. (2023). DynAMoS: The Dynamic Affective Movie Clip Database for Subjectivity Analysis. *Proceedings of the 11th International Conference on Affective Computing and Intelligent Interaction (ACII).*


## Abstract

In this paper, we describe the design, collection, and validation of a new video database that includes holistic and dynamic emotion ratings from 83 participants watching 22 affective movie clips. In contrast to previous work in Affective Computing, which pursued a single “ground truth” label for the affective content of each moment of each video (e.g., by averaging the ratings of 2 to 7 trained participants), we embrace the subjectivity inherent to emotional experiences and provide the full distribution of all participants’ ratings (with an average of 76.7 raters per video). We argue that this choice represents a paradigm shift with the potential to unlock new research directions, generate new hypotheses, and inspire novel methods in the Affective Computing community. We also describe several interdisciplinary use cases for the database: to provide dynamic norms for emotion elicitation studies (e.g., in psychology, medicine, and neuroscience), to train and test affective content analysis algorithms (e.g., for dynamic emotion recognition, video summarization, and movie recommendation), and to study subjectivity in emotional reactions (e.g., to identify moments of emotional ambiguity or ambivalence within movies, identify predictors of subjectivity, and develop personalized affective content analysis algorithms). The database is made freely available to researchers for noncommercial use at <https://dynamos.mgb.org>.
