---
title: "Social risk and depression: Evidence from manual and automatic facial expression analysis"
type: "proceeding"
author: "Girard, Cohn, Mahoor, et al."
year: "2013"
publication: "FG"
preprint: ""
doi: "https://doi.org/10.1109/FG.2013.6553748"
materials: ""
toc: false
categories:
  - clinical
  - nonverbal
  - proceeding
---

## Citation (APA 7)

> Girard, J. M., Cohn, J. F., Mahoor, M. H., Mavadati, S. M., & Rosenwald, D. P. (2013). Social risk and depression: Evidence from manual and automatic facial expression analysis. *Proceedings of the 10th IEEE International Conference on Automatic Face & Gesture Recognition (FG)*, 1–8.

## Abstract

Investigated the relationship between change over time in severity of depression symptoms and facial expression. Depressed participants were followed over the course of treatment and video recorded during a series of clinical interviews. Facial expressions were analyzed from the video using both manual and automatic systems. Automatic and manual coding were highly consistent for FACS action units, and showed similar effects for change over time in depression severity. For both systems, when symptom severity was high, participants made more facial expressions associated with contempt, smiled less, and those smiles that occurred were more likely to be accompanied by facial actions associated with contempt. These results are consistent with the “social risk hypothesis” of depression. According to this hypothesis, when symptoms are severe, depressed participants withdraw from other people in order to protect themselves from anticipated rejection, scorn, and social exclusion. As their symptoms fade, participants send more signals indicating a willingness to affiliate. The finding that automatic facial expression analysis was both consistent with manual coding and produced the same pattern of depression effects suggests that automatic facial expression analysis may be ready for use in behavioral and clinical science.
