---
title: "Reconsidering the Duchenne Smile: Indicator of Positive Emotion or Artifact of Smile Intensity?"
type: "proceeding"
author: "Girard, Shandar, Liu, et al."
year: "2019"
publication: "ACII"
preprint: "https://psyarxiv.com/z2jvd/"
doi: "https://doi.org/10.1109/ACII.2019.8925535"
materials: "https://osf.io/t7e2d/"
toc: false
categories:
  - nonverbal
  - affective
  - proceeding
---

## Citation (APA 7)

> Girard, J. M., Shandar, G., Liu, Z., Cohn, J. F., Yin, L., & Morency, L.-P. (2019). Reconsidering the Duchenne smile: Indicator of positive emotion or artifact of smile intensity? *Proceedings of the 8th International Conference on Affective Computing and Intelligent Interaction (ACII)*, 594–599.

## Abstract

The Duchenne smile hypothesis is that smiles that include eye constriction (AU6) are the product of genuine positive emotion, whereas smiles that do not are either falsified or related to negative emotion. This hypothesis has become very influential and is often used in scientific and applied settings to justify the inference that a smile is either true or false. However, empirical support for this hypothesis has been equivocal and some researchers have proposed that, rather than being a reliable indicator of positive emotion, AU6 may just be an artifact produced by intense smiles. Initial support for this proposal has been found when comparing smiles related to genuine and feigned positive emotion; however, it has not yet been examined when comparing smiles related to genuine positive and negative emotion. The current study addressed this gap in the literature by examining spontaneous smiles from 136 participants during the elicitation of amusement, embarrassment, fear, and pain (from the BP4D+ dataset). Bayesian multilevel regression models were used to quantify the associations between AU6 and self-reported amusement while controlling for smile intensity. Models were estimated to infer amusement from AU6 and to explain the intensity of AU6 using amusement. In both cases, controlling for smile intensity substantially reduced the hypothesized association, whereas the effect of smile intensity itself was quite large and reliable. These results provide further evidence that the Duchenne smile is likely an artifact of smile intensity rather than a reliable and unique indicator of genuine positive emotion.
