---
title: "Multimodal spontaneous emotion corpus for human behavior analysis"
type: "proceeding"
author: "Zhang, Girard, Wu, et al."
year: "2016"
publication: "CVPR"
preprint: ""
doi: "https://doi.org/10.1109/CVPR.2016.374"
materials: ""
toc: false
categories:
  - database
  - nonverbal
  - affective
  - proceeding
---

## Citation (APA 7)

> Zhang, Z., Girard, J. M., Wu, Y., Zhang, X., Liu, P., Ciftci, U., Canavan, S., Reale, M., Horowitz, A., Yang, H., Cohn, J. F., Ji, Q., & Yin, L. (2016). Multimodal spontaneous emotion corpus for human behavior analysis. *Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition (CVPR)*, 3438–3446.

## Abstract

Emotion is expressed in multiple modalities, yet most research has considered at most one or two. This stems in part from the lack of large, diverse, well-annotated, multimodal databases with which to develop and test algorithms. We present a well-annotated, multimodal, multidimensional spontaneous emotion corpus of 140 participants. Emotion inductions were highly varied. Data were acquired from a variety of sensors of the face that included high-resolution 3D dynamic imaging, high-resolution 2D video, and thermal (infrared) sensing, and contact physiological sensors that included electrical conductivity of the skin, respiration, blood pressure, and heart rate. Facial expression was annotated for both the occurrence and intensity of facial action units from 2D video by experts in the Facial Action Coding System (FACS). The corpus further includes derived features from 3D, 2D, and IR (infrared) sensors and baseline results for facial expression and action unit detection. The entire corpus will be made available to the research community.
